# Generated by Django 4.2.5 on 2023-09-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="middle_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.IntegerField(default=0),
        ),
    ]
