# Generated by Django 4.2.5 on 2024-04-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_alter_student_student_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="abbreviation",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="campus",
            field=models.CharField(
                choices=[
                    ("Main Campus", "Main Campus"),
                    ("Town Campus", "Town Campus"),
                    ("Western Campus", "Western Campus"),
                    ("Kitengela Campus", "Kitengela Campus"),
                ],
                default="Main Campus",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_type",
            field=models.CharField(
                choices=[
                    ("Self Sponsored Student", "Self Sponsored Student"),
                    ("Government Sponsored Student", "Government Sponsored Student"),
                ],
                default="Self Sponsored Student",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="study_mode",
            field=models.CharField(
                choices=[
                    ("Full Time", "Full Time"),
                    ("Part Time", "Part Time"),
                    ("Distance Learning", "Distance Learning"),
                ],
                default="Full Time",
                max_length=255,
            ),
        ),
    ]
