# Generated by Django 4.2.5 on 2024-04-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_course_abbreviation_alter_student_campus_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecturer",
            name="lec_id",
        ),
        migrations.AddField(
            model_name="lecturer",
            name="assessees",
            field=models.ManyToManyField(blank=True, to="myapp.student"),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="assessor_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="phone_number",
            field=models.CharField(default="test", max_length=12),
            preserve_default=False,
        ),
    ]
