# Generated by Django 4.2.5 on 2024-04-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_lecturer_lec_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="phone_number",
            field=models.CharField(max_length=255),
        ),
    ]
