# Generated by Django 4.2.5 on 2024-04-14 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_alter_lecturer_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecturer",
            name="assessees",
        ),
        migrations.AddField(
            model_name="student",
            name="assessor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.lecturer",
            ),
        ),
    ]
