# Generated by Django 4.2.5 on 2024-04-16 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_remove_lecturer_assessees_student_assessor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="assessor",
        ),
        migrations.RemoveField(
            model_name="student",
            name="att_form",
        ),
        migrations.RemoveField(
            model_name="student",
            name="course",
        ),
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
        migrations.DeleteModel(
            name="Lecturer",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
