# Generated by Django 4.2.5 on 2024-04-16 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lecturer", "0001_initial"),
        ("myapp", "0012_remove_student_assessor_remove_student_att_form_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("middle_name", models.CharField(max_length=255, null=True)),
                ("phone_number", models.IntegerField(default=0)),
                ("email", models.EmailField(max_length=254)),
                ("adm_no", models.CharField(max_length=12)),
                (
                    "study_mode",
                    models.CharField(
                        choices=[
                            ("Full Time", "Full Time"),
                            ("Part Time", "Part Time"),
                            ("Distance Learning", "Distance Learning"),
                        ],
                        default="Full Time",
                        max_length=255,
                    ),
                ),
                (
                    "campus",
                    models.CharField(
                        choices=[
                            ("Main Campus", "Main Campus"),
                            ("Town Campus", "Town Campus"),
                            ("Western Campus", "Western Campus"),
                            ("Kitengela Campus", "Kitengela Campus"),
                        ],
                        default="Main Campus",
                        max_length=255,
                    ),
                ),
                (
                    "student_type",
                    models.CharField(
                        choices=[
                            ("Self Sponsored Student", "Self Sponsored Student"),
                            (
                                "Government Sponsored Student",
                                "Government Sponsored Student",
                            ),
                        ],
                        default="Self Sponsored Student",
                        max_length=255,
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lecturer.lecturer",
                    ),
                ),
                (
                    "att_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.attachmentform",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.course"
                    ),
                ),
            ],
        ),
    ]
