# Generated by Django 4.2.5 on 2024-05-07 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="att_form",
        ),
        migrations.CreateModel(
            name="StudentAttachmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_name", models.CharField(max_length=100)),
                ("adm_no", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
                ("course", models.CharField(max_length=100)),
                ("study_mode", models.CharField(max_length=100)),
                ("campus", models.CharField(max_length=100)),
                ("student_type", models.CharField(max_length=100)),
                ("org_name", models.CharField(max_length=100)),
                ("org_location", models.CharField(max_length=100)),
                ("date_joined", models.DateField(max_length=100)),
                ("end_date", models.DateField(max_length=100)),
                ("status", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
            ],
        ),
    ]
