# Generated by Django 4.2.5 on 2024-05-08 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lecturer", "0001_initial"),
        ("student", "0002_remove_student_att_form_studentattachmentmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="assessor",
        ),
        migrations.AddField(
            model_name="studentattachmentmodel",
            name="assessor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lecturer.lecturer",
            ),
        ),
    ]
