# Generated by Django 4.2.5 on 2024-05-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_remove_student_assessor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_type",
            field=models.CharField(
                choices=[
                    ("Self Sponsored Student", "Self Sponsored Student"),
                    ("Government Sponsored Student", "Government Sponsored Student"),
                    ("Extra Sponsored Student", "Extra Sponsored Student"),
                ],
                default="Self Sponsored Student",
                max_length=255,
            ),
        ),
    ]
